services:
  # Backend API service
  - type: web
    name: crmspace-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: USE_REDIS
        value: true
      - key: GOOGLE_CALLBACK_URL
        value: https://crmspace-backend.onrender.com/auth/google/callback
      - key: FRONTEND_URL
        value: https://crmspace-frontend.onrender.com
      - key: SESSION_SECRET
        value: your-session-secret
      - key: MONGO_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/crm
      - key: REDIS_URL
        value: redis://default:password@host:port
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret
      - key: OPENAI_API_KEY
        value: your-openai-api-key
      - key: NEBIUS_API_KEY
        value: your-nebius-api-key
      - key: GITHUB_TOKEN
        value: your-github-token

  # Frontend web app
  - type: web
    name: crmspace-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://crmspace-backend.onrender.com

  # Stream consumer service
  - type: web
    name: crmspace-stream-consumer
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/services/streamConsumer.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_REDIS
        value: true
      - key: SESSION_SECRET
        value: your-session-secret
      - key: MONGO_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/crm
      - key: REDIS_URL
        value: redis://default:password@host:port
